feat: use customer access tokens for customer logins
bigcommerce/catalyst pull request #1262
Opened 2024-08-14 16:50 UTC by chanceaclark

## What/Why?
Uses the new approach of using Customer Access Tokens (**CATs**)  when login in as a customer. This change utilized the Storefront API Token (**APIT**) instead of the Storefront Customer Impersonation Token (**CIT**) to authenticate requests as CATs will only be generated using a APIT.

> [!TIP]
> Reviewing by commit will be helpful.

## Testing
Every commit was individually tested so that Catalyst could keep working depending on the state. If need be, try to roll back to a previous commit if not working correctly.

2024-09-13 19:07 UTC, deini approved these changes

2024-09-13 19:41 UTC, jorgemoya approved these changes

2024-09-18 16:33 UTC, matthewvolk requested changes

2024-09-18 16:33 UTC, matthewvolk commented on integrations/algolia/integration.patch
Now that I'm thinking about it, this `patch` file is only compatible with the latest core tag. If we merge this and someone creates a new Catalyst storefront at the currently available core tag, this patch won't work for them since the new CAT changes are in `main` but not in the currently available core tag.

2024-09-18 16:33 UTC, matthewvolk commented on integrations/makeswift/integration.patch
Same here

2024-09-30 19:24 UTC, matthewvolk approved these changes

2024-11-04 17:06 UTC, merged