feat: add Error page and ErrorBoundary
bigcommerce/catalyst pull request #1827
Opened 2024-12-31 20:07 UTC by jordanarldt

## What/Why?
- Use the `Error` component from VIBES
- Modify existing `error` page to use this component
- Add an ErrorBoundary in `(default)` route to maintain layout structure when error occurs

## Testing

![image](https://github.com/user-attachments/assets/99d28887-14af-4875-8469-0463f33153ed)

2024-12-31 21:24 UTC, migueloller requested changes
Looks good. Do we have a way to test this?

2024-12-31 21:24 UTC, migueloller commented on core/app/[locale]/(default)/error.tsx
> +export default lazy(() => import('../_components/error'));
How come we're doing this? Next.js files are already lazily loaded so this shouldn't be necessary

2024-12-31 21:24 UTC, migueloller commented on core/app/[locale]/(default)/error.tsx
> +export default lazy(() => import('../_components/error'));
We should define a new component here and render the error component so it's clear we're passing `retry` as a function and not a server action

2024-12-31 22:08 UTC, jordanarldt commented
> Looks good. Do we have a way to test this?

@migueloller I tested on my sandbox store, since my category pages are still returning 500 errors due to that weird `nuqs` error when I have no product filters 👍  That's how I got the screenshots.

If we were to make functional tests for this behavior though, not entirely sure how we'd go about testing - we'd have to force an internal error.

2024-12-31 22:43 UTC, migueloller commented
> > Looks good. Do we have a way to test this?
> 
> @migueloller I tested on my sandbox store, since my category pages are still returning 500 errors due to that weird `nuqs` error when I have no product filters 👍 That's how I got the screenshots.
> 
> If we were to make functional tests for this behavior though, not entirely sure how we'd go about testing - we'd have to force an internal error.

We should be able to do this by passing a streamable prop that throws whenever we implement the test

2025-01-02 15:10 UTC, jordanarldt commented
> We should be able to do this by passing a streamable prop that throws whenever we implement the test

@migueloller Yeah, that's what I had in mind also. For a functional / E2E test though, not sure how we'd force the error there 💭

2025-01-02 18:50 UTC, jorgemoya approved these changes
LGTM. Having two error boundaries makes sense, even though we duplicate code, which seems off.

2025-01-02 18:50 UTC, jorgemoya commented on core/app/[locale]/error.tsx
> -export default lazy(() => import('./_components/error'));
We were doing this to prevent `next-intl` from loading as part of the initial bundle, but at this point I don't know if this is happening anyway since we use the context. More info [here](https://next-intl.dev/docs/environments/error-files).

2025-01-03 19:06 UTC, migueloller approved these changes

2025-01-06 15:35 UTC, merged